### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuprexDE** [Creeperface01/Holograms#6]
Hello!

I have created a PlaceHolder and want to insert it in a hologram. But then there is an error.The placeholder works, but not on Holograms.

https://paste.devin.id/evemesavux.cs

**Comment by Creeperface01** [comment]
What kind of placeholder is it? I tested with static and also visitor placeholders but without any error

**Comment by SuprexDE** [comment]
its a static placeholder

**Comment by Creeperface01** [comment]
I wasn't able to reproduce it.
