### ISSUE TITLE
Holograms disappeared

### ISSUE THREAD

**Issue by Bluefrosting** [Creeperface01/Holograms#8]
My holograms randomly disappeared. I checked the console and there weren't any errors present. When I try to create one, I can see it for a split second but then it disappears again! I'm not sure what could be causing this error.

**Comment by Creeperface01** [comment]
> My holograms randomly disappeared. I checked the console and there weren't any errors present. When I try to create one, I can see it for a split second but then it disappears again! I'm not sure what could be causing this error.

Try running /save-all after creating a hologram

**Comment by Bluefrosting** [comment]
Just tried it and it didn't work. When I create one it won't even show up. If I angle my in-game view at a specific angle the hologram will appear but then disappear when I move.
